### ISSUE TITLE
Configure Supabase to serve a sample podcast

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#22]
A podcast should be a streamable audio file. In the future, we will add support for transcripts of podcasts, so watch out for that.

We can take a sample audio file from [MixKit](https://mixkit.co/free-stock-music/).

**Acceptance criteria**:
- An app is created on Supabase
- A link is created to fetch a sample audio file 

**Artifacts**:
- A link to the audio file

**Comment by khaledismaeel** [comment]
When you say "an app is created on Supabase" do you mean the (currently empty) app is deployed there? Or do you mean an empty project has been created?

**Comment by illright** [comment]
Supabase isn't a frontend hosting platform, it's a database with superpowers and pressy buttons. Our frontend is going to be deployed to [Cloudflare Pages](https://pages.cloudflare.com/).

By creating an app on Supabase I mean initializing a database, setting up tables and stuff.

**Comment by khaledismaeel** [comment]
Okay so I created an organization and a project for our work. Configured a primitive database for storing podcast and episode metadata and uploaded a sample podcast [file](https://sklgqhbbbhticzdgegcj.supabase.in/storage/v1/object/sign/podcast-files/lex_ai_garry_kasparov.mp3?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwb2RjYXN0LWZpbGVzL2xleF9haV9nYXJyeV9rYXNwYXJvdi5tcDMiLCJpYXQiOjE2NDQwOTM4NTQsImV4cCI6MTk1OTQ1Mzg1NH0.BQC9zJuKxeVNKLI4pc7QWweEBNqF98wD2TypKD0OWo8).

I thought I would configure authentication as well, but it seems that we need an up and running application before we proceed further with it, so I'll leave it for later.

I will need to add you guys to the organization in order to check the correctness of work, let's do it on telegram.
