### ISSUE TITLE
Configure CD to Cloudflare Pages

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#38]
**Acceptance criteria**:
* The hostname of the app should be `cast-iu.pages.dev` (`cast` is already taken)
* A URL to the app should be added to the top of the README
* Every PR should generate a preview deployment on a subdomain of the original hostname
* Every commit to `main` that passes static checks and test suites should update the main deployment

**Comment by khaledismaeel** [comment]
Apparently GitHub only authorizes the repository's owner to Cloudflare. We need @aabounegm for this one.

**Comment by aabounegm** [comment]
For future reference, here are the problems I faced and workarounds I needed to get it to work:
- There is no way to override the default install step command, which is `npm install`, which caused problems with our preinstall script. Even [Evan You complained about it](https://twitter.com/youyuxi/status/1470940983994957826). The solution was to add `NPM_FLAGS=--version` to the environment variables in CloudFlare to disable it and install manually using `npm install -g pnpm && pnpm i --store=node_modules/.pnpm-store && pnpm build` (as suggested by [this post](https://community.cloudflare.com/t/add-pnpm-to-pre-installed-cloudflare-pages-tools/288514/4)) for the build step
- The default Node version is too old and some features (like optional chaining in the Svelte compiler itself) were not working. This was simple, just `NODE_VERSION=16.14.0` in the environment variables.

I also faced another build error that I didn't have locally for some reason:
```
> Using @sveltejs/adapter-auto
> 404 /media/cc0-audio/t-rex-roar.mp3 (linked from /)
...
ELIFECYCLE  Command failed with exit code 1.
Failed: build command exited with code: 1
```
which made sense because we don't have this file, so a PR is on its way to fix that.
