### ISSUE TITLE
Protect the `main` branch

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#4]

**Comment by VanishMax** [comment]
@aabounegm Please, configure the Pages settings in GitHub like so:

![image](https://user-images.githubusercontent.com/29180358/151658781-8860f565-46d6-4a4c-b0e7-74eb0c3d5831.png)

It is needed for the workflow of publishing the presentation to your GitHub Pages

**Comment by aabounegm** [comment]
The only protection I applied for now is requiring a PR with one approval before merging. I don't personally like the "dismiss stale approvals" option, but we can vote on it. I will leave this issue open until the CI is all configured so that I require passing _status checks_ as well (if that's desirable), and maybe requiring signed commits (if everyone agrees with Khaled)

@VanishMax done.

**Comment by illright** [comment]
CI checks are already set up, so you can make them required. As for signing commits, guess we didn't agree on it after all as everyone seems to be pushing unsigned commits.

That said, after enabling the requirement of CI checks, this issue may be closed

**Comment by aabounegm** [comment]
Ok, and I noticed that #7 is about that anyway, so issue could have been closed since the beginning.
